### ISSUE TITLE
希望4K和8K之间增加HDR选项

### ISSUE THREAD

**Issue by Jimmisama** [AHCorn/Bilibili-Auto-Quality#2]
谢谢谢谢

**Comment by AHCorn** [comment]
感谢反馈，下周内会更新并增加HDR选项，但我个人的设备大多不支持HDR，所以发布后有劳您实际测试。![image](https://github.com/AHCorn/Bilibili-Auto-Quality/assets/42889600/76d231f2-4367-40bc-9766-c4bfd73e046c)

**Comment by SkylineLch** [comment]
希望同时增加杜比视界的选项，目前我个人用的aw3225是支持杜比视界的，可以手动开启。
今年应该有几款显示器都支持杜比视界，尽管windows上的杜比支持并不完善，但开启后效果是比nvidia的自动HDR强不少的。

**Comment by AHCorn** [comment]
除了两位提到的画质的适配外，我个人使用中遇到的大部分问题今天一次性解决了下：

1. 大会员有时候判断失败导致切换到非会员画质
增加了一个当前画质判断，如果当前选择的画质是大会员画质，那么也认定用户为大会员，避免了画质被调到1080P。

2. 切换速度慢
原来是在 onload（页面完成加载） 事件后的 7.5 秒进行切换，但是由于B站使用了异步加载，现在改成了监听大会员标识附近元素是否完成加载，加载完成后的 3.5 秒进行切换，其实一定程度上也解决了没加载出来导致大会员判断出错。

3.切换失败
之前测试的版本用的是循环选择，但会导致用户切换不了画质，而目前的切换逻辑有时候会出现切换失败的问题，这次更新了在切换画质七秒后再检验一次画质是否被切换到目标画质，如果没有的话就再切换一次。

4.切换逻辑问题
如果用户选择的画质没有找到的话脚本就没有进行实质性的操作，这次更新了在未找到目标画质的情况下自动选择最高可用画质。

目前待办仅剩增加对直播的画质适配，但看了下是有些难度的，我个人不常看直播，可能会就此搁置了。

杜比视界的适配目前未经测试，有劳自行测试下。

感谢二位的适配建议，如果有其它任何问题，也欢迎随时反馈。

**Comment by Jimmisama** [comment]
谢谢，可用
